name: God Apply Monday Fill

on:
  schedule:
    # JST 月曜 06:15 = UTC 日曜 21:15
    - cron: "15 21 * * 0"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run god_apply_monday_fill
        run: |
          python -u scripts/god_apply_monday_fill.py

      - name: Commit god_state.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/data/god_state.json
          git commit -m "Apply god_state (monday fill)" || echo "No changes"
          git push